import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Aparna Shaju Mern Stack Developer',
  description: 'Generated by create next app',
   icons: {
    icon: '/images/Aparna_Shaju.jpg',
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
